% Autogenerated file: Thu Nov 17 09:41:04 2022
function writeCodeInfoFcn


% Load a ComponentInterface object from IR
codeIRInfoStruct = load('tlc\codeIRInfo.mat');
codeInfo = codeIRInfoStruct.codeInfo;

prmIdxMap = containers.Map;




wr = coder.internal.writeDataInterfacesToCodeDescriptor("Model_6DOF",pwd) ;
wr.writeName(codeInfo.Name);



skippedParameters = [];


                            
    % Built-In Type: 0
        Type_0_R0_V0_C0 = coder.types.Double;
        Type_0_R0_V0_C0.Name = 'double';
    Type_0_R0_V0_C0.Identifier = 'real_T';
    Type_0_R0_V0_C0.ReadOnly   = 0;
    Type_0_R0_V0_C0.Volatile   = 0;
        
    % Matrix Type
    Type_58_R0_V0_C0 = coder.types.Matrix;
    Type_58_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_58_R0_V0_C0.Dimensions = [1,6];
        Type_58_R0_V0_C0.SymbolicDimensions = Type_58_R0_V0_C0.SymbolicDimensions;
        

            
    % Matrix Type
    Type_43_R0_V0_C0 = coder.types.Matrix;
    Type_43_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_43_R0_V0_C0.Dimensions = [1,1];
        Type_43_R0_V0_C0.SymbolicDimensions = Type_43_R0_V0_C0.SymbolicDimensions;
                                skippedParameters(end+1) = 2;
























                        skippedParameters(end+1) = 14;


            
    % Matrix Type
    Type_51_R0_V0_C0 = coder.types.Matrix;
    Type_51_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_51_R0_V0_C0.Dimensions = [3,1];
        Type_51_R0_V0_C0.SymbolicDimensions = Type_51_R0_V0_C0.SymbolicDimensions;
        



                        skippedParameters(end+1) = 17;








            
    % Matrix Type
    Type_56_R0_V0_C0 = coder.types.Matrix;
    Type_56_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_56_R0_V0_C0.Dimensions = [616,1];
        Type_56_R0_V0_C0.SymbolicDimensions = Type_56_R0_V0_C0.SymbolicDimensions;
        



            
    % Matrix Type
    Type_55_R0_V0_C0 = coder.types.Matrix;
    Type_55_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_55_R0_V0_C0.Dimensions = [2914,1];
        Type_55_R0_V0_C0.SymbolicDimensions = Type_55_R0_V0_C0.SymbolicDimensions;
        

            
    % Matrix Type
    Type_54_R0_V0_C0 = coder.types.Matrix;
    Type_54_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_54_R0_V0_C0.Dimensions = [550,1];
        Type_54_R0_V0_C0.SymbolicDimensions = Type_54_R0_V0_C0.SymbolicDimensions;
        

            
    % Matrix Type
    Type_52_R0_V0_C0 = coder.types.Matrix;
    Type_52_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_52_R0_V0_C0.Dimensions = [904,1];
        Type_52_R0_V0_C0.SymbolicDimensions = Type_52_R0_V0_C0.SymbolicDimensions;
        

            
    % Matrix Type
    Type_53_R0_V0_C0 = coder.types.Matrix;
    Type_53_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_53_R0_V0_C0.Dimensions = [564,1];
        Type_53_R0_V0_C0.SymbolicDimensions = Type_53_R0_V0_C0.SymbolicDimensions;
        

            
    % Matrix Type
    Type_57_R0_V0_C0 = coder.types.Matrix;
    Type_57_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_57_R0_V0_C0.Dimensions = [200,1];
        Type_57_R0_V0_C0.SymbolicDimensions = Type_57_R0_V0_C0.SymbolicDimensions;
        















            
    % Matrix Type
    Type_29_R0_V0_C0 = coder.types.Matrix;
    Type_29_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_29_R0_V0_C0.Dimensions = [2914,3];
        Type_29_R0_V0_C0.SymbolicDimensions = Type_29_R0_V0_C0.SymbolicDimensions;
        

            
    % Matrix Type
    Type_31_R0_V0_C0 = coder.types.Matrix;
    Type_31_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_31_R0_V0_C0.Dimensions = [550,3];
        Type_31_R0_V0_C0.SymbolicDimensions = Type_31_R0_V0_C0.SymbolicDimensions;
        

            
    % Matrix Type
    Type_33_R0_V0_C0 = coder.types.Matrix;
    Type_33_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_33_R0_V0_C0.Dimensions = [904,3];
        Type_33_R0_V0_C0.SymbolicDimensions = Type_33_R0_V0_C0.SymbolicDimensions;
        

            
    % Matrix Type
    Type_39_R0_V0_C0 = coder.types.Matrix;
    Type_39_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_39_R0_V0_C0.Dimensions = [564,3];
        Type_39_R0_V0_C0.SymbolicDimensions = Type_39_R0_V0_C0.SymbolicDimensions;
        

































            
    % Matrix Type
    Type_30_R0_V0_C0 = coder.types.Matrix;
    Type_30_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_30_R0_V0_C0.Dimensions = [616,3];
        Type_30_R0_V0_C0.SymbolicDimensions = Type_30_R0_V0_C0.SymbolicDimensions;
        











            
    % Matrix Type
    Type_36_R0_V0_C0 = coder.types.Matrix;
    Type_36_R0_V0_C0.BaseType   = Type_0_R0_V0_C0;
        Type_36_R0_V0_C0.Dimensions = [200,3];
        Type_36_R0_V0_C0.SymbolicDimensions = Type_36_R0_V0_C0.SymbolicDimensions;
        











































































            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            








































































































            tmpArgs         = [];
    tmpActualArgs   = [];
    tmpRet          = coder.types.Argument.empty;
    tmpActualReturn = RTW.DataInterface.empty;


    func_Initialize_Prototype = coder.types.Prototype;
    func_Initialize_Prototype.Arguments  = tmpArgs;
    func_Initialize_Prototype.Return     = tmpRet;

        func_Initialize_Prototype.HeaderFile = 'Model_6DOF.h';
    func_Initialize_Prototype.SourceFile = 'Model_6DOF.c';

    func_Initialize_Interface = RTW.FunctionInterface;
    func_Initialize_Interface.Prototype    = func_Initialize_Prototype;
    func_Initialize_Interface.ActualArgs   = tmpActualArgs;
    func_Initialize_Interface.ActualReturn = tmpActualReturn;

        func_Initialize_Prototype.Name = 'Model_6DOF_initialize';
    time_constant = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, -1));
        func_Initialize_Interface.Timing = time_constant;
        codeInfo.InitializeFunctions =  [codeInfo.InitializeFunctions, func_Initialize_Interface'];
        func_Initialize_Interface.IsInitializeFunction = true;

                            tmpArgs         = [];
    tmpActualArgs   = [];
    tmpRet          = coder.types.Argument.empty;
    tmpActualReturn = RTW.DataInterface.empty;


            





    func_UpdateContStates_Prototype = coder.types.Prototype;
    func_UpdateContStates_Prototype.Arguments  = tmpArgs;
    func_UpdateContStates_Prototype.Return     = tmpRet;

        func_UpdateContStates_Prototype.HeaderFile = 'Model_6DOF.h';
    func_UpdateContStates_Prototype.SourceFile = 'Model_6DOF.c';

    func_UpdateContStates_Interface = RTW.FunctionInterface;
    func_UpdateContStates_Interface.Prototype    = func_UpdateContStates_Prototype;
    func_UpdateContStates_Interface.ActualArgs   = tmpActualArgs;
    func_UpdateContStates_Interface.ActualReturn = tmpActualReturn;

    time_1 = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, 1));
        func_UpdateContStates_Interface.Timing = time_1;
            func_UpdateContStates_Prototype.Name = 'Model_6DOF_step';
            codeInfo.OutputFunctions =  [codeInfo.OutputFunctions, func_UpdateContStates_Interface'];

                    
                


                tmpArgs         = [];
    tmpActualArgs   = [];
    tmpRet          = coder.types.Argument.empty;
    tmpActualReturn = RTW.DataInterface.empty;


    func_Terminate_Prototype = coder.types.Prototype;
    func_Terminate_Prototype.Arguments  = tmpArgs;
    func_Terminate_Prototype.Return     = tmpRet;

        func_Terminate_Prototype.HeaderFile = 'Model_6DOF.h';
    func_Terminate_Prototype.SourceFile = 'Model_6DOF.c';

    func_Terminate_Interface = RTW.FunctionInterface;
    func_Terminate_Interface.Prototype    = func_Terminate_Prototype;
    func_Terminate_Interface.ActualArgs   = tmpActualArgs;
    func_Terminate_Interface.ActualReturn = tmpActualReturn;

    time_constant = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, -1));
        func_Terminate_Interface.Timing = time_constant;
                func_Terminate_Prototype.Name = ['Model_6DOF_terminate'];
        codeInfo.TerminateFunctions =  [codeInfo.TerminateFunctions, func_Terminate_Interface'];


    




            % Opaque Data Type
            type_RTModel  = coder.types.Opaque;
            type_RTModel.Identifier = 'RT_MODEL_Model_6DOF_T';
            

        % Pointer Type: Pointer to type_RTModel
        Ptrtype_RTModel_1_0 = coder.types.Pointer;
            Ptrtype_RTModel_1_0.BaseType = type_RTModel;
        Ptrtype_RTModel_1_0.ReadOnly = 1;
        Ptrtype_RTModel_1_0.Volatile = 0;
        




        % Variable: Var_RTModel
        Var_RTModel = RTW.Variable(Ptrtype_RTModel_1_0.BaseType, 'Model_6DOF_M_');
        Var_RTModel.Owner           = 'Model_6DOF';
        Var_RTModel.DeclarationFile = 'Model_6DOF.h';
            Var_RTModel.DefinitionFile  = 'Model_6DOF.c';
        

        % Pointer Variable: PtrVar_RTModel
        PtrVar_RTModel = RTW.PointerVariable(Ptrtype_RTModel_1_0, 'Model_6DOF_M', Var_RTModel);
        
        PtrVar_RTModel.Owner = Var_RTModel.Owner;
            PtrVar_RTModel.DeclarationFile = Var_RTModel.DeclarationFile;
            PtrVar_RTModel.DefinitionFile = Var_RTModel.DefinitionFile;

        % Data Interface: idata_RTModel
            empty_timing = RTW.TimingInterface.empty;
        idata_RTModel = RTW.DataInterface('', 'RTModel', PtrVar_RTModel, empty_timing);
        









    







































































































































































































































if ~isempty(skippedParameters)
wr.removeSkippedParameters(codeInfo.Parameters(skippedParameters));
codeInfo.Parameters(skippedParameters) = [];
end

        codeInfo.InternalData = [codeInfo.InternalData, idata_RTModel];
    wr.addInternalData(idata_RTModel);

% Handling Right-Click Builds
ss = rtwprivate('getSourceSubsystemHandle',codeInfo.GraphicalPath);
% Check if Rt-Click build, then re-map SIDs
if ~isempty(ss) && rtwprivate('rtwattic','hasSIDMap')
codeInfo = modifyCodeInfoForSubsystemBuild(ss, codeInfo, wr);
end

wr.writeFunctionInterfaces(codeInfo);
wr.writeServerCallPoints(codeInfo);



wr.closeRepo();
    if exist('expInports', 'var')
    save codeInfo.mat codeInfo expInports;
    else
    save codeInfo.mat codeInfo;
    end
returnVal = 1;

% End Function: writeCodeInfoFcn

function data = uniquifyDataAccess(list)
data = RTW.DataInterface.empty;
for idx=1:numel(list)
if ~isPresentDI(data, list(idx))
data(end+1) = list(idx); %#ok<AGROW>
end
end
% End Function: uniquifyDataAccess

function isPresent = isPresentDI(list, di)
isPresent = false;
for idx = 1:numel(list)
if isequal(list(idx), di)
isPresent = true;
break
end
end

function idx = getIndexFromTimingInternalId(internalIdVec, internalId)
idx = find(internalIdVec == internalId);
if (isempty(idx) || (length(idx) > 1))
ciMsg = 'Time object cannot be empty';
ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
throw(ciExc);
end
% End Function: getIndexFromTimingInternalId

function checkDataGraphicalNames(ciName, rtwName)
if (strcmp(ciName, rtwName) ~= 1)
ciMsg = ['Name mismatch: ', ciName, ' and ', rtwName];
ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
throw(ciExc);
end
% End Function: checkDataGraphicalNames

function iData = getInternalDataByName(iDataVec, iDataName)
iData = RTW.DataInterface.empty;
for idxData = 1:numel(iDataVec)
if strcmp(iDataName, iDataVec(idxData).GraphicalName)
iData(end+1) = iDataVec(idxData);
break
end
end
if (isempty(iData) || (length(iData) > 1))
ciMsg = 'Internal Data object cannot be empty';
ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
throw(ciExc);
end
% End Function: getInternalDataByName

function iData = getInternalDataByVariableName(iDataVec, iDataVariableName)
iData = RTW.DataInterface.empty;
for idxData = 1:numel(iDataVec)
if strcmp(iDataVariableName, iDataVec(idxData).Implementation.VariableName)
iData = iDataVec(idxData);
break
end
end
if isempty(iData)
ciMsg = 'Internal Data object cannot be empty';
ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
throw(ciExc);
end
% End Function: getInternalDataByVariableName

function codeInfo = modifyCodeInfoForSubsystemBuild(ss, codeInfo, wr)
    % Extract Subsystem Build Map from AtticData
    Subsystem_Build_Mapping = rtwprivate('rtwattic','getSIDMap');

    % Parameters
    for i = 1:length(codeInfo.Parameters)
    sid = codeInfo.Parameters(i).SID;

    sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
    wr.updateSIDForSubsystemBuild("Parameter", i, sid, codeInfo.Parameters(i));
    codeInfo.Parameters(i).SID = sid;
    end

    % Data Stores
    for i = 1:length(codeInfo.DataStores)
    sid = codeInfo.DataStores(i).SID;

    sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
    codeInfo.DataStores(i).SID = sid;
    wr.updateSIDForSubsystemBuild("DataStore", i, sid);

    end

    % Inports
    for i = 1:length(codeInfo.Inports)
    sid = codeInfo.Inports(i).SID;

    sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
    codeInfo.Inports(i).SID = sid;
    wr.updateSIDForSubsystemBuild("Inport", i, sid);

    end

    % Outports
    for i = 1:length(codeInfo.Outports)
    sid = codeInfo.Outports(i).SID;

    sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
    codeInfo.Outports(i).SID = sid;
    wr.updateSIDForSubsystemBuild("Outport", i, sid);

    end

